name: Build Maven Package

on:
  push:
    branches: [ "dev-*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.PACKAGE_READ_ONLY_TOKEN }}"
            }]
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Push to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/MC_*.jar
